// This file is auto-generated by scripts/generate_countries.mjs

export interface Country {
  id: string;
  name: string;
  tagline: string;
  description: string;
  image: string;
  highlights: string[];
  capital: string;
  language: string;
  population: string;
  geographyText: string[];
  geographyImage: string;
  cultureFeatures: { title: string; description: string; icon: string }[];
  region: string;
  iso2: string;
}

export const countries: Country[] = [
  {
    id: "libya",
    name: "Libya",
    tagline: "Heart of North Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Libya, a remarkable destination in North Africa.",
    image: "https://loremflickr.com/1200/800/Libya,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Tripoli",
    language: "Arabic",
    population: "Various",
    region: "North Africa",
    iso2: "ly",
    geographyImage: "https://loremflickr.com/800/600/Libya,nature/all",
    geographyText: [
      "Libya features diverse landscapes that define the beautiful North Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Libya is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Libya.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "morocco",
    name: "Morocco",
    tagline: "The Western Kingdom",
    description: "A sensory overload of colorful souks, stunning Islamic architecture, and the endless Sahara.",
    image: "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?q=80&w=2000&auto=format&fit=crop",
    highlights: ["Nature", "Culture", "History"],
    capital: "Rabat",
    language: "Arabic, Berber",
    population: "Various",
    region: "North Africa",
    iso2: "ma",
    geographyImage: "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?q=80&w=800&auto=format&fit=crop",
    geographyText: [
      "Morocco\'s landscape is defined by the rugged Atlas Mountains that run down the spine of the country, separating the mild Mediterranean and Atlantic coastlines from the harsh Sahara Desert. The highest peak, Mount Toubkal, is a popular trekking destination.",
      "Beyond the mountains, the golden dunes of the Sahara stretch out endlessly. The coastal regions are fertile and historically significant, hosting ancient cities and vibrant modern hubs."
    ],
    cultureFeatures: [
      { title: "Medina Life", description: "Lose yourself in the labyrinthine alleys of ancient medinas, where artisans craft leather, brass, and ceramics using centuries-old techniques.", icon: "users" },
      { title: "Mint Tea Tradition", description: "The serving of sweet mint tea is a cornerstone of Moroccan hospitality, representing friendship and welcoming visitors.", icon: "paint" }
    ]
  },
  {
    id: "w-sahara",
    name: "W. Sahara",
    tagline: "Heart of North Africa",
    description: "Discover the untamed beauty and rich cultural heritage of W. Sahara, a remarkable destination in North Africa.",
    image: "https://loremflickr.com/1200/800/Western%20Sahara,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Laayoune",
    language: "Arabic, Spanish",
    population: "Various",
    region: "North Africa",
    iso2: "eh",
    geographyImage: "https://loremflickr.com/800/600/Western%20Sahara,nature/all",
    geographyText: [
      "W. Sahara features diverse landscapes that define the beautiful North Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of W. Sahara is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in W. Sahara.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "algeria",
    name: "Algeria",
    tagline: "Heart of North Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Algeria, a remarkable destination in North Africa.",
    image: "https://loremflickr.com/1200/800/Algeria,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Algiers",
    language: "Arabic, Berber",
    population: "Various",
    region: "North Africa",
    iso2: "dz",
    geographyImage: "https://loremflickr.com/800/600/Algeria,nature/all",
    geographyText: [
      "Algeria features diverse landscapes that define the beautiful North Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Algeria is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Algeria.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "tunisia",
    name: "Tunisia",
    tagline: "Heart of North Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Tunisia, a remarkable destination in North Africa.",
    image: "https://loremflickr.com/1200/800/Tunisia,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Tunis",
    language: "Arabic",
    population: "Various",
    region: "North Africa",
    iso2: "tn",
    geographyImage: "https://loremflickr.com/800/600/Tunisia,nature/all",
    geographyText: [
      "Tunisia features diverse landscapes that define the beautiful North Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Tunisia is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Tunisia.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "egypt",
    name: "Egypt",
    tagline: "Cradle of Civilization",
    description: "Step back in time to the land of pharaohs, pyramids, and the life-giving Nile River.",
    image: "https://images.unsplash.com/photo-1539650116574-8efeb43e2750?q=80&w=2000&auto=format&fit=crop",
    highlights: ["Nature", "Culture", "History"],
    capital: "Cairo",
    language: "Arabic",
    population: "Various",
    region: "North Africa",
    iso2: "eg",
    geographyImage: "https://images.unsplash.com/photo-1600527352352-7104e1c12ce3?q=80&w=800&auto=format&fit=crop",
    geographyText: [
      "Egypt is largely defined by the world\'s longest river, the Nile, which snakes through the eastern part of the country, providing a fertile lifeline amidst the surrounding desert. The vast Sahara Desert covers the majority of Egypt\'s landmass, creating a harsh but beautiful expanse of sand dunes and rocky plateaus.",
      "To the east, the Red Sea coast offers stunning coral reefs and rugged mountainous terrain, making it a stark contrast to the lush Nile valley and the arid Western Desert."
    ],
    cultureFeatures: [
      { title: "Ancient Wonders", description: "Home to the Great Pyramids of Giza, the Sphinx, and countless temples that stand as testaments to one of history\'s most powerful civilizations.", icon: "paint" },
      { title: "Vibrant Bazaars", description: "Experience the sensory overload of bustling souks, where the scent of spices, intricate textiles, and traditional music fill the air.", icon: "users" }
    ]
  },
  {
    id: "sudan",
    name: "Sudan",
    tagline: "Heart of North Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Sudan, a remarkable destination in North Africa.",
    image: "https://loremflickr.com/1200/800/Sudan,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Khartoum",
    language: "Arabic, English",
    population: "Various",
    region: "North Africa",
    iso2: "sd",
    geographyImage: "https://loremflickr.com/800/600/Sudan,nature/all",
    geographyText: [
      "Sudan features diverse landscapes that define the beautiful North Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Sudan is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Sudan.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "eritrea",
    name: "Eritrea",
    tagline: "Heart of East Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Eritrea, a remarkable destination in East Africa.",
    image: "https://loremflickr.com/1200/800/Eritrea,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Asmara",
    language: "Tigrinya, Arabic",
    population: "Various",
    region: "East Africa",
    iso2: "er",
    geographyImage: "https://loremflickr.com/800/600/Eritrea,nature/all",
    geographyText: [
      "Eritrea features diverse landscapes that define the beautiful East Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Eritrea is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Eritrea.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "djibouti",
    name: "Djibouti",
    tagline: "Heart of East Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Djibouti, a remarkable destination in East Africa.",
    image: "https://loremflickr.com/1200/800/Djibouti,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Djibouti City",
    language: "French, Arabic",
    population: "Various",
    region: "East Africa",
    iso2: "dj",
    geographyImage: "https://loremflickr.com/800/600/Djibouti,nature/all",
    geographyText: [
      "Djibouti features diverse landscapes that define the beautiful East Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Djibouti is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Djibouti.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "somalia",
    name: "Somalia",
    tagline: "Heart of East Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Somalia, a remarkable destination in East Africa.",
    image: "https://loremflickr.com/1200/800/Somalia,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Mogadishu",
    language: "Somali, Arabic",
    population: "Various",
    region: "East Africa",
    iso2: "so",
    geographyImage: "https://loremflickr.com/800/600/Somalia,nature/all",
    geographyText: [
      "Somalia features diverse landscapes that define the beautiful East Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Somalia is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Somalia.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "ethiopia",
    name: "Ethiopia",
    tagline: "Heart of East Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Ethiopia, a remarkable destination in East Africa.",
    image: "https://loremflickr.com/1200/800/Ethiopia,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Addis Ababa",
    language: "Amharic",
    population: "Various",
    region: "East Africa",
    iso2: "et",
    geographyImage: "https://loremflickr.com/800/600/Ethiopia,nature/all",
    geographyText: [
      "Ethiopia features diverse landscapes that define the beautiful East Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Ethiopia is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Ethiopia.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "s-sudan",
    name: "S. Sudan",
    tagline: "Heart of East Africa",
    description: "Discover the untamed beauty and rich cultural heritage of S. Sudan, a remarkable destination in East Africa.",
    image: "https://loremflickr.com/1200/800/South%20Sudan,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Juba",
    language: "English",
    population: "Various",
    region: "East Africa",
    iso2: "ss",
    geographyImage: "https://loremflickr.com/800/600/South%20Sudan,nature/all",
    geographyText: [
      "S. Sudan features diverse landscapes that define the beautiful East Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of S. Sudan is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in S. Sudan.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "uganda",
    name: "Uganda",
    tagline: "Heart of East Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Uganda, a remarkable destination in East Africa.",
    image: "https://loremflickr.com/1200/800/Uganda,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Kampala",
    language: "English, Swahili",
    population: "Various",
    region: "East Africa",
    iso2: "ug",
    geographyImage: "https://loremflickr.com/800/600/Uganda,nature/all",
    geographyText: [
      "Uganda features diverse landscapes that define the beautiful East Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Uganda is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Uganda.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "rwanda",
    name: "Rwanda",
    tagline: "Heart of East Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Rwanda, a remarkable destination in East Africa.",
    image: "https://loremflickr.com/1200/800/Rwanda,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Kigali",
    language: "Kinyarwanda, English, French",
    population: "Various",
    region: "East Africa",
    iso2: "rw",
    geographyImage: "https://loremflickr.com/800/600/Rwanda,nature/all",
    geographyText: [
      "Rwanda features diverse landscapes that define the beautiful East Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Rwanda is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Rwanda.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "burundi",
    name: "Burundi",
    tagline: "Heart of East Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Burundi, a remarkable destination in East Africa.",
    image: "https://loremflickr.com/1200/800/Burundi,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Gitega",
    language: "Kirundi, French",
    population: "Various",
    region: "East Africa",
    iso2: "bi",
    geographyImage: "https://loremflickr.com/800/600/Burundi,nature/all",
    geographyText: [
      "Burundi features diverse landscapes that define the beautiful East Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Burundi is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Burundi.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "kenya",
    name: "Kenya",
    tagline: "Pride of Africa",
    description: "The classic African safari destination, home to the Great Migration and the majestic Maasai Mara.",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?q=80&w=2000&auto=format&fit=crop",
    highlights: ["Nature", "Culture", "History"],
    capital: "Nairobi",
    language: "Swahili, English",
    population: "Various",
    region: "East Africa",
    iso2: "ke",
    geographyImage: "https://images.unsplash.com/photo-1547471080-7fc2caa7f5a6?q=80&w=800&auto=format&fit=crop",
    geographyText: [
      "Kenya\'s geography is as varied as its wildlife. The Great Rift Valley slices through the country from north to south, creating a dramatic landscape of lakes, volcanoes, and escarpments. Mount Kenya, the second-highest peak in Africa, towers over the central highlands, its snow-capped peak a stark contrast to the surrounding savanna.",
      "To the southeast, the coastline offers pristine white-sand beaches bordering the warm Indian Ocean. The northern regions are arid and semi-desert, characterized by rugged terrain and vital oases."
    ],
    cultureFeatures: [
      { title: "Maasai Traditions", description: "The iconic Maasai people continue to live semi-nomadic lifestyles, preserving their distinct red attire, jumping dances, and deep connection to the land.", icon: "users" },
      { title: "Swahili Coast", description: "A historic blend of African, Arab, and Indian influences that birthed the Swahili language and a unique coastal architectural style.", icon: "paint" }
    ]
  },
  {
    id: "tanzania",
    name: "Tanzania",
    tagline: "Wild at Heart",
    description: "Witness the sheer scale of the Serengeti and the towering heights of Mount Kilimanjaro.",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?q=80&w=2000&auto=format&fit=crop",
    highlights: ["Nature", "Culture", "History"],
    capital: "Dodoma",
    language: "Swahili, English",
    population: "Various",
    region: "East Africa",
    iso2: "tz",
    geographyImage: "https://images.unsplash.com/photo-1547471080-7fc2caa7f5a6?q=80&w=800&auto=format&fit=crop",
    geographyText: [
      "Tanzania is home to Africa\'s highest peak, Mount Kilimanjaro, a dormant volcano that rises dramatically from the plains. The country also encompasses a significant portion of the Great Rift Valley, which holds massive lakes like Victoria, Tanganyika, and Nyasa.",
      "The vast Serengeti plains in the north are the stage for the immense annual wildebeest migration. Off the eastern coast lies the Zanzibar Archipelago, known for its pristine beaches and historic Stone Town."
    ],
    cultureFeatures: [
      { title: "Rich Tribal Tapestry", description: "Over 120 distinct ethnic groups call Tanzania home, creating a peaceful and vibrant mosaic of languages, dances, and traditions.", icon: "users" },
      { title: "Spice Island Heritage", description: "Zanzibar\'s history as a major trading hub is evident in its heavily spiced cuisine and the ornate wooden doors of its historic buildings.", icon: "paint" }
    ]
  },
  {
    id: "seychelles",
    name: "Seychelles",
    tagline: "Heart of East Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Seychelles, a remarkable destination in East Africa.",
    image: "https://loremflickr.com/1200/800/Seychelles,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Victoria",
    language: "French, English",
    population: "Various",
    region: "East Africa",
    iso2: "sc",
    geographyImage: "https://loremflickr.com/800/600/Seychelles,nature/all",
    geographyText: [
      "Seychelles features diverse landscapes that define the beautiful East Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Seychelles is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Seychelles.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "mozambique",
    name: "Mozambique",
    tagline: "Heart of East Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Mozambique, a remarkable destination in East Africa.",
    image: "https://loremflickr.com/1200/800/Mozambique,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Maputo",
    language: "Portuguese",
    population: "Various",
    region: "East Africa",
    iso2: "mz",
    geographyImage: "https://loremflickr.com/800/600/Mozambique,nature/all",
    geographyText: [
      "Mozambique features diverse landscapes that define the beautiful East Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Mozambique is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Mozambique.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "malawi",
    name: "Malawi",
    tagline: "Heart of East Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Malawi, a remarkable destination in East Africa.",
    image: "https://loremflickr.com/1200/800/Malawi,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Lilongwe",
    language: "English, Chichewa",
    population: "Various",
    region: "East Africa",
    iso2: "mw",
    geographyImage: "https://loremflickr.com/800/600/Malawi,nature/all",
    geographyText: [
      "Malawi features diverse landscapes that define the beautiful East Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Malawi is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Malawi.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "comoros",
    name: "Comoros",
    tagline: "Heart of East Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Comoros, a remarkable destination in East Africa.",
    image: "https://loremflickr.com/1200/800/Comoros,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Moroni",
    language: "Comorian, Arabic, French",
    population: "Various",
    region: "East Africa",
    iso2: "km",
    geographyImage: "https://loremflickr.com/800/600/Comoros,nature/all",
    geographyText: [
      "Comoros features diverse landscapes that define the beautiful East Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Comoros is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Comoros.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "madagascar",
    name: "Madagascar",
    tagline: "The Eighth Continent",
    description: "An evolutionary wonderland teeming with unique wildlife and dramatic landscapes found nowhere else on Earth.",
    image: "https://images.unsplash.com/photo-1518414922567-5d8205f15f01?q=80&w=2000&auto=format&fit=crop",
    highlights: ["Nature", "Culture", "History"],
    capital: "Antananarivo",
    language: "Malagasy, French",
    population: "Various",
    region: "East Africa",
    iso2: "mg",
    geographyImage: "https://images.unsplash.com/photo-1506451000858-a4db79ab33b5?q=80&w=800&auto=format&fit=crop",
    geographyText: [
      "As the world\'s fourth-largest island, Madagascar\'s isolation has resulted in a landscape completely unique to itself. The eastern coast is a steep escarpment covered in dense tropical rainforests, while the western side is characterized by dry deciduous forests and the iconic Avenue of the Baobabs.",
      "The central highlands are terraced with rice paddies and feature cooler climates. The island is also dotted with bizarre geological formations, such as the limestone pinnacles of the Tsingy de Bemaraha."
    ],
    cultureFeatures: [
      { title: "Endemic Ecosystems", description: "Famed for its incredible biodiversity, with lemurs, chameleons, and bizarre flora that evolved entirely independently from the mainland.", icon: "paint" },
      { title: "Austronesian Roots", description: "The Malagasy culture is a fascinating blend of Southeast Asian, African, and European influences, visible in their language, agriculture, and complex burial rituals.", icon: "users" }
    ]
  },
  {
    id: "mauritius",
    name: "Mauritius",
    tagline: "Heart of East Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Mauritius, a remarkable destination in East Africa.",
    image: "https://loremflickr.com/1200/800/Mauritius,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Port Louis",
    language: "English, French",
    population: "Various",
    region: "East Africa",
    iso2: "mu",
    geographyImage: "https://loremflickr.com/800/600/Mauritius,nature/all",
    geographyText: [
      "Mauritius features diverse landscapes that define the beautiful East Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Mauritius is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Mauritius.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "eswatini",
    name: "eSwatini",
    tagline: "Heart of South Africa",
    description: "Discover the untamed beauty and rich cultural heritage of eSwatini, a remarkable destination in South Africa.",
    image: "https://loremflickr.com/1200/800/Eswatini,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Mbabane",
    language: "Swazi, English",
    population: "Various",
    region: "South Africa",
    iso2: "sz",
    geographyImage: "https://loremflickr.com/800/600/Eswatini,nature/all",
    geographyText: [
      "eSwatini features diverse landscapes that define the beautiful South Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of eSwatini is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in eSwatini.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "south-africa",
    name: "South Africa",
    tagline: "The Rainbow Nation",
    description: "Experience the vibrant heart of the Rainbow Nation, from the iconic Table Mountain to the untamed wilderness of Kruger National Park.",
    image: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?q=80&w=2000&auto=format&fit=crop",
    highlights: ["Nature", "Culture", "History"],
    capital: "Pretoria",
    language: "12 Official Languages",
    population: "Various",
    region: "South Africa",
    iso2: "za",
    geographyImage: "https://images.unsplash.com/photo-1576485290814-1c72aa4faa8e?q=80&w=800&auto=format&fit=crop",
    geographyText: [
      "South Africa boasts an incredible diversity of landscapes, encompassing a staggering 2,798 kilometers of coastline that stretches along both the South Atlantic and Indian Oceans. To the north lie the dry, dusty expanses of the Kalahari Desert, contrasting sharply with the lush, green canopy of the Tsitsikamma forest along the Garden Route.",
      "The interior is dominated by a vast, flat, and sparsely populated scrubland known as the Karoo. The eastern coastline is well-watered and tropical, while the southwest enjoys a Mediterranean climate, fostering the world-renowned Cape Floristic Region, one of the six floral kingdoms of the world."
    ],
    cultureFeatures: [
      { title: "Diverse Heritage", description: "A beautiful amalgamation of numerous cultures, including Zulu, Xhosa, Afrikaans, and English influences, reflected in its music, art, and daily life.", icon: "users" },
      { title: "Artisan Crafts", description: "Renowned for vibrant beadwork, intricate pottery, and woven baskets that tell stories of ancient traditions and modern resilience.", icon: "paint" }
    ]
  },
  {
    id: "lesotho",
    name: "Lesotho",
    tagline: "Heart of South Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Lesotho, a remarkable destination in South Africa.",
    image: "https://loremflickr.com/1200/800/Lesotho,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Maseru",
    language: "Sesotho, English",
    population: "Various",
    region: "South Africa",
    iso2: "ls",
    geographyImage: "https://loremflickr.com/800/600/Lesotho,nature/all",
    geographyText: [
      "Lesotho features diverse landscapes that define the beautiful South Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Lesotho is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Lesotho.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "namibia",
    name: "Namibia",
    tagline: "Heart of South Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Namibia, a remarkable destination in South Africa.",
    image: "https://loremflickr.com/1200/800/Namibia,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Windhoek",
    language: "English",
    population: "Various",
    region: "South Africa",
    iso2: "na",
    geographyImage: "https://loremflickr.com/800/600/Namibia,nature/all",
    geographyText: [
      "Namibia features diverse landscapes that define the beautiful South Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Namibia is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Namibia.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "angola",
    name: "Angola",
    tagline: "Heart of South Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Angola, a remarkable destination in South Africa.",
    image: "https://loremflickr.com/1200/800/Angola,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Luanda",
    language: "Portuguese",
    population: "Various",
    region: "South Africa",
    iso2: "ao",
    geographyImage: "https://loremflickr.com/800/600/Angola,nature/all",
    geographyText: [
      "Angola features diverse landscapes that define the beautiful South Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Angola is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Angola.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "botswana",
    name: "Botswana",
    tagline: "Heart of South Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Botswana, a remarkable destination in South Africa.",
    image: "https://loremflickr.com/1200/800/Botswana,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Gaborone",
    language: "English, Setswana",
    population: "Various",
    region: "South Africa",
    iso2: "bw",
    geographyImage: "https://loremflickr.com/800/600/Botswana,nature/all",
    geographyText: [
      "Botswana features diverse landscapes that define the beautiful South Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Botswana is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Botswana.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "zimbabwe",
    name: "Zimbabwe",
    tagline: "Heart of South Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Zimbabwe, a remarkable destination in South Africa.",
    image: "https://loremflickr.com/1200/800/Zimbabwe,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Harare",
    language: "16 Official Languages",
    population: "Various",
    region: "South Africa",
    iso2: "zw",
    geographyImage: "https://loremflickr.com/800/600/Zimbabwe,nature/all",
    geographyText: [
      "Zimbabwe features diverse landscapes that define the beautiful South Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Zimbabwe is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Zimbabwe.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "zambia",
    name: "Zambia",
    tagline: "Heart of South Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Zambia, a remarkable destination in South Africa.",
    image: "https://loremflickr.com/1200/800/Zambia,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Lusaka",
    language: "English",
    population: "Various",
    region: "South Africa",
    iso2: "zm",
    geographyImage: "https://loremflickr.com/800/600/Zambia,nature/all",
    geographyText: [
      "Zambia features diverse landscapes that define the beautiful South Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Zambia is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Zambia.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "dem-rep-congo",
    name: "Dem. Rep. Congo",
    tagline: "Heart of Central Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Dem. Rep. Congo, a remarkable destination in Central Africa.",
    image: "https://loremflickr.com/1200/800/DR%20Congo,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Kinshasa",
    language: "French",
    population: "Various",
    region: "Central Africa",
    iso2: "cd",
    geographyImage: "https://loremflickr.com/800/600/DR%20Congo,nature/all",
    geographyText: [
      "Dem. Rep. Congo features diverse landscapes that define the beautiful Central Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Dem. Rep. Congo is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Dem. Rep. Congo.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "congo",
    name: "Congo",
    tagline: "Heart of Central Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Congo, a remarkable destination in Central Africa.",
    image: "https://loremflickr.com/1200/800/Republic%20of%20the%20Congo,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Brazzaville",
    language: "French",
    population: "Various",
    region: "Central Africa",
    iso2: "cg",
    geographyImage: "https://loremflickr.com/800/600/Republic%20of%20the%20Congo,nature/all",
    geographyText: [
      "Congo features diverse landscapes that define the beautiful Central Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Congo is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Congo.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "gabon",
    name: "Gabon",
    tagline: "Heart of Central Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Gabon, a remarkable destination in Central Africa.",
    image: "https://loremflickr.com/1200/800/Gabon,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Libreville",
    language: "French",
    population: "Various",
    region: "Central Africa",
    iso2: "ga",
    geographyImage: "https://loremflickr.com/800/600/Gabon,nature/all",
    geographyText: [
      "Gabon features diverse landscapes that define the beautiful Central Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Gabon is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Gabon.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "eq-guinea",
    name: "Eq. Guinea",
    tagline: "Heart of Central Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Eq. Guinea, a remarkable destination in Central Africa.",
    image: "https://loremflickr.com/1200/800/Equatorial%20Guinea,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Malabo",
    language: "Spanish, French, Portuguese",
    population: "Various",
    region: "Central Africa",
    iso2: "gq",
    geographyImage: "https://loremflickr.com/800/600/Equatorial%20Guinea,nature/all",
    geographyText: [
      "Eq. Guinea features diverse landscapes that define the beautiful Central Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Eq. Guinea is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Eq. Guinea.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "s-o-tom-and-principe",
    name: "São Tomé and Principe",
    tagline: "Heart of Central Africa",
    description: "Discover the untamed beauty and rich cultural heritage of São Tomé and Principe, a remarkable destination in Central Africa.",
    image: "https://loremflickr.com/1200/800/S%C3%A3o%20Tom%C3%A9%20and%20Pr%C3%ADncipe,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "São Tomé",
    language: "Portuguese",
    population: "Various",
    region: "Central Africa",
    iso2: "st",
    geographyImage: "https://loremflickr.com/800/600/S%C3%A3o%20Tom%C3%A9%20and%20Pr%C3%ADncipe,nature/all",
    geographyText: [
      "São Tomé and Principe features diverse landscapes that define the beautiful Central Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of São Tomé and Principe is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in São Tomé and Principe.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "central-african-rep",
    name: "Central African Rep.",
    tagline: "Heart of Central Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Central African Rep., a remarkable destination in Central Africa.",
    image: "https://loremflickr.com/1200/800/Central%20African%20Republic,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Bangui",
    language: "Sango, French",
    population: "Various",
    region: "Central Africa",
    iso2: "cf",
    geographyImage: "https://loremflickr.com/800/600/Central%20African%20Republic,nature/all",
    geographyText: [
      "Central African Rep. features diverse landscapes that define the beautiful Central Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Central African Rep. is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Central African Rep..", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "chad",
    name: "Chad",
    tagline: "Heart of Central Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Chad, a remarkable destination in Central Africa.",
    image: "https://loremflickr.com/1200/800/Chad,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "N'Djamena",
    language: "Arabic, French",
    population: "Various",
    region: "Central Africa",
    iso2: "td",
    geographyImage: "https://loremflickr.com/800/600/Chad,nature/all",
    geographyText: [
      "Chad features diverse landscapes that define the beautiful Central Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Chad is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Chad.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "cameroon",
    name: "Cameroon",
    tagline: "Heart of Central Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Cameroon, a remarkable destination in Central Africa.",
    image: "https://loremflickr.com/1200/800/Cameroon,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Yaoundé",
    language: "French, English",
    population: "Various",
    region: "Central Africa",
    iso2: "cm",
    geographyImage: "https://loremflickr.com/800/600/Cameroon,nature/all",
    geographyText: [
      "Cameroon features diverse landscapes that define the beautiful Central Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Cameroon is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Cameroon.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "nigeria",
    name: "Nigeria",
    tagline: "Heart of West Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Nigeria, a remarkable destination in West Africa.",
    image: "https://loremflickr.com/1200/800/Nigeria,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Abuja",
    language: "English",
    population: "Various",
    region: "West Africa",
    iso2: "ng",
    geographyImage: "https://loremflickr.com/800/600/Nigeria,nature/all",
    geographyText: [
      "Nigeria features diverse landscapes that define the beautiful West Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Nigeria is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Nigeria.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "mali",
    name: "Mali",
    tagline: "Heart of West Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Mali, a remarkable destination in West Africa.",
    image: "https://loremflickr.com/1200/800/Mali,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Bamako",
    language: "French",
    population: "Various",
    region: "West Africa",
    iso2: "ml",
    geographyImage: "https://loremflickr.com/800/600/Mali,nature/all",
    geographyText: [
      "Mali features diverse landscapes that define the beautiful West Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Mali is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Mali.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "niger",
    name: "Niger",
    tagline: "Heart of West Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Niger, a remarkable destination in West Africa.",
    image: "https://loremflickr.com/1200/800/Niger,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Niamey",
    language: "French",
    population: "Various",
    region: "West Africa",
    iso2: "ne",
    geographyImage: "https://loremflickr.com/800/600/Niger,nature/all",
    geographyText: [
      "Niger features diverse landscapes that define the beautiful West Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Niger is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Niger.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "mauritania",
    name: "Mauritania",
    tagline: "Heart of West Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Mauritania, a remarkable destination in West Africa.",
    image: "https://loremflickr.com/1200/800/Mauritania,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Nouakchott",
    language: "Arabic",
    population: "Various",
    region: "West Africa",
    iso2: "mr",
    geographyImage: "https://loremflickr.com/800/600/Mauritania,nature/all",
    geographyText: [
      "Mauritania features diverse landscapes that define the beautiful West Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Mauritania is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Mauritania.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "cape-verde",
    name: "Cape Verde",
    tagline: "Heart of West Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Cape Verde, a remarkable destination in West Africa.",
    image: "https://loremflickr.com/1200/800/Cape%20Verde,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Praia",
    language: "Portuguese",
    population: "Various",
    region: "West Africa",
    iso2: "cv",
    geographyImage: "https://loremflickr.com/800/600/Cape%20Verde,nature/all",
    geographyText: [
      "Cape Verde features diverse landscapes that define the beautiful West Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Cape Verde is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Cape Verde.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "senegal",
    name: "Senegal",
    tagline: "Heart of West Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Senegal, a remarkable destination in West Africa.",
    image: "https://loremflickr.com/1200/800/Senegal,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Dakar",
    language: "French",
    population: "Various",
    region: "West Africa",
    iso2: "sn",
    geographyImage: "https://loremflickr.com/800/600/Senegal,nature/all",
    geographyText: [
      "Senegal features diverse landscapes that define the beautiful West Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Senegal is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Senegal.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "gambia",
    name: "Gambia",
    tagline: "Heart of West Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Gambia, a remarkable destination in West Africa.",
    image: "https://loremflickr.com/1200/800/Gambia,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Banjul",
    language: "English",
    population: "Various",
    region: "West Africa",
    iso2: "gm",
    geographyImage: "https://loremflickr.com/800/600/Gambia,nature/all",
    geographyText: [
      "Gambia features diverse landscapes that define the beautiful West Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Gambia is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Gambia.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "guinea-bissau",
    name: "Guinea-Bissau",
    tagline: "Heart of West Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Guinea-Bissau, a remarkable destination in West Africa.",
    image: "https://loremflickr.com/1200/800/Guinea-Bissau,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Bissau",
    language: "Portuguese",
    population: "Various",
    region: "West Africa",
    iso2: "gw",
    geographyImage: "https://loremflickr.com/800/600/Guinea-Bissau,nature/all",
    geographyText: [
      "Guinea-Bissau features diverse landscapes that define the beautiful West Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Guinea-Bissau is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Guinea-Bissau.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "guinea",
    name: "Guinea",
    tagline: "Heart of West Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Guinea, a remarkable destination in West Africa.",
    image: "https://loremflickr.com/1200/800/Guinea,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Conakry",
    language: "French",
    population: "Various",
    region: "West Africa",
    iso2: "gn",
    geographyImage: "https://loremflickr.com/800/600/Guinea,nature/all",
    geographyText: [
      "Guinea features diverse landscapes that define the beautiful West Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Guinea is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Guinea.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "sierra-leone",
    name: "Sierra Leone",
    tagline: "Heart of West Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Sierra Leone, a remarkable destination in West Africa.",
    image: "https://loremflickr.com/1200/800/Sierra%20Leone,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Freetown",
    language: "English",
    population: "Various",
    region: "West Africa",
    iso2: "sl",
    geographyImage: "https://loremflickr.com/800/600/Sierra%20Leone,nature/all",
    geographyText: [
      "Sierra Leone features diverse landscapes that define the beautiful West Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Sierra Leone is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Sierra Leone.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "liberia",
    name: "Liberia",
    tagline: "Heart of West Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Liberia, a remarkable destination in West Africa.",
    image: "https://loremflickr.com/1200/800/Liberia,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Monrovia",
    language: "English",
    population: "Various",
    region: "West Africa",
    iso2: "lr",
    geographyImage: "https://loremflickr.com/800/600/Liberia,nature/all",
    geographyText: [
      "Liberia features diverse landscapes that define the beautiful West Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Liberia is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Liberia.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "c-te-d-ivoire",
    name: "Côte d'Ivoire",
    tagline: "Heart of West Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Côte d'Ivoire, a remarkable destination in West Africa.",
    image: "https://loremflickr.com/1200/800/Ivory%20Coast,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Yamoussoukro",
    language: "French",
    population: "Various",
    region: "West Africa",
    iso2: "ci",
    geographyImage: "https://loremflickr.com/800/600/Ivory%20Coast,nature/all",
    geographyText: [
      "Côte d'Ivoire features diverse landscapes that define the beautiful West Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Côte d'Ivoire is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Côte d'Ivoire.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "burkina-faso",
    name: "Burkina Faso",
    tagline: "Heart of West Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Burkina Faso, a remarkable destination in West Africa.",
    image: "https://loremflickr.com/1200/800/Burkina%20Faso,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Ouagadougou",
    language: "French",
    population: "Various",
    region: "West Africa",
    iso2: "bf",
    geographyImage: "https://loremflickr.com/800/600/Burkina%20Faso,nature/all",
    geographyText: [
      "Burkina Faso features diverse landscapes that define the beautiful West Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Burkina Faso is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Burkina Faso.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "ghana",
    name: "Ghana",
    tagline: "Heart of West Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Ghana, a remarkable destination in West Africa.",
    image: "https://loremflickr.com/1200/800/Ghana,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Accra",
    language: "English",
    population: "Various",
    region: "West Africa",
    iso2: "gh",
    geographyImage: "https://loremflickr.com/800/600/Ghana,nature/all",
    geographyText: [
      "Ghana features diverse landscapes that define the beautiful West Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Ghana is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Ghana.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "togo",
    name: "Togo",
    tagline: "Heart of West Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Togo, a remarkable destination in West Africa.",
    image: "https://loremflickr.com/1200/800/Togo,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Lomé",
    language: "French",
    population: "Various",
    region: "West Africa",
    iso2: "tg",
    geographyImage: "https://loremflickr.com/800/600/Togo,nature/all",
    geographyText: [
      "Togo features diverse landscapes that define the beautiful West Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Togo is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Togo.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
  {
    id: "benin",
    name: "Benin",
    tagline: "Heart of West Africa",
    description: "Discover the untamed beauty and rich cultural heritage of Benin, a remarkable destination in West Africa.",
    image: "https://loremflickr.com/1200/800/Benin,landscape/all",
    highlights: ["Nature", "Culture", "History"],
    capital: "Porto-Novo",
    language: "French",
    population: "Various",
    region: "West Africa",
    iso2: "bj",
    geographyImage: "https://loremflickr.com/800/600/Benin,nature/all",
    geographyText: [
      "Benin features diverse landscapes that define the beautiful West Africa region.",
      "From bustling cities to tranquil nature reserves, the geography of Benin is truly awe-inspiring."
    ],
    cultureFeatures: [
      { title: "Rich Heritage", description: "Experience the deep-rooted traditions and vibrant lifestyles of the people in Benin.", icon: "users" },
      { title: "Art & Music", description: "The local art and music scene reflects a unique blend of historical influences and modern creativity.", icon: "paint" }
    ]
  },
];
